apiVersion: v1
kind: PersistentVolume
metadata:
  name: notebooks-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.3
    path: "/exports/notebooks"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: notebooks-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi