apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-worker
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.240.0.3
    path: "/exports/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spark-worker
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi